# Generated by Django 4.1 on 2023-03-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_mensalidade_configuracoes_vl_mensalidade_and_more'),
        ('pelada', '0002_pelada_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelada.pelada')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaGoleiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('goleiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.goleiro')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelada.pelada')),
            ],
        ),
    ]
