# Generated by Django 4.1 on 2023-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='Nome da pelada')),
                ('horario', models.TimeField(verbose_name='Horário da pelada')),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor por mensalista')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Saldo em caixa')),
            ],
        ),
    ]
