# Generated by Django 4.1 on 2023-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('pix', models.CharField(max_length=100, null=True, verbose_name='Chave Pix')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('pix', models.CharField(max_length=100, null=True, verbose_name='Chave Pix')),
                ('tipo', models.IntegerField(choices=[(1, 'Avulso'), (2, 'Mensalista')], default=1, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
