# Generated by Django 4.1 on 2023-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goleiro_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goleiro',
            name='pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='goleiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
