# Generated by Django 4.1 on 2023-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_goleiro_pix_alter_goleiro_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoes',
            old_name='mensalidade',
            new_name='vl_mensalidade',
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='vl_avulso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor por avulso'),
            preserve_default=False,
        ),
    ]
