# Generated by Django 4.1 on 2023-03-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_mensalidade_configuracoes_vl_mensalidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoes',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
    ]
